server {
    server_name edwared.cloud www.edwared.cloud;

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/edwared_cloud_v2/edwared_cloud.sock;
    }

    location /rpandemo01/ {
        include proxy_params;
        proxy_pass http://localhost:5001/;
        proxy_set_header X-Forwarded-Prefix /rpandemo01;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/edwared.cloud/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/edwared.cloud/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.edwared.cloud) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = edwared.cloud) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name edwared.cloud www.edwared.cloud;
    return 404; # managed by Certbot
}
